language: objective-c
osx_image: xcode7.2

before_install:
  # bring in Cedar and other dependencies
  - git submodule update --init
  # try to start the iPhone simulator at least once
  - open -b com.apple.iphonesimulator

matrix:
  include:
     - env: BUILD_SDK_VERSION="9.2" SIMULATOR_VERSIONS="8.4" SIMULATOR_DEVICES="iPhone 5,iPhone 5s"
     - env: BUILD_SDK_VERSION="9.2" SIMULATOR_VERSIONS="9.2" SIMULATOR_DEVICES="iPhone 5,iPhone 5s"

script: rake travis

