language: objective-c
osx_image: xcode7.2

before_install:
  - git submodule update --init

matrix:
  include:
     - env: BUILD_SDK_VERSION="9.2" SIMULATOR_VERSIONS="8.4" SIMULATOR_DEVICES="iPhone 5,iPhone 5s"
     - env: BUILD_SDK_VERSION="9.2" SIMULATOR_VERSIONS="9.2" SIMULATOR_DEVICES="iPhone 5,iPhone 5s"

script: rake travis

